version: '3.4'

services:
  api:
    container_name: vase-api
    restart: always
    build: ./api
    ports:
      - '3000:3000'
    links:
      - 'mongo'

  mongo:
    image: mongo
    container_name: vase-mongo
    volumes:
      - ./volumes/mongo-volume:/data/db
    restart: always
    ports:
      - '27017:27017'

  mongo-express:
    image: mongo-express
    container_name: vase-mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root

  floyd:
    container_name: floyd
    build: ./floyd
    volumes:
      - ./floyd:/usr/src/app
    ports:
      - 5000:80
